config/routes.rb
CaseBase::Application.routes.draw do
  resources :references

  resources :documents

  devise_for :users

	get 'about' => 'home#about'

   root :to => 'home#index'

end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
  attr_accessible :Address, :City, :Email, :FirstN, :Interests, :LastN, :Organization, :PhoneN, :State

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :description
  validates :description, presence: true, :length => {:in => 6..50}
  belongs_to :user

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :consultant
  attr_accessible :ExperienceLevel, :Name, :References

end

app/models/reference.rb
class Reference < ActiveRecord::Base
  attr_accessible :description, :email, :firstN, :lastN, :phone, :user_id
  validate :firstN, :lastN, :email, :description, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,      #add in :recoverable
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstn, :lastn, :addressl1, :addressl2, :city, :state, :zip, :type
  validates :zip, :length => { :is => 5 }
  validates :type, :length => {:is => 1}
  validates :email, :uniqueness => true
  validates :email, :firstn, :lastn, :password, :type, :city, :state, :presence => true


  # attr_accessible :title, :body
  has_many :documents
  has_many :references
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/business_controller.rb
class BusinessController < ApplicationController
end

app/controllers/consultant_controller.rb
class ConsultantController < ApplicationController
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json

  before_filter :authenticate_user!

  def index
    @documents = current_user.documents.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = current_user.documents.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = current_user.documents.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def about
  end

  def user_profile
  end

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  # GET /references
  # GET /references.json

  before_filter :authenticate_user!

  def index
    @references = current_user.references.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @references }
    end
  end

  # GET /references/1
  # GET /references/1.json
  def show
    @reference = current_user.references.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/new
  # GET /references/new.json
  def new
    @reference = current_user.references.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reference }
    end
  end

  # GET /references/1/edit
  def edit
    @reference = current_user.references.find(params[:id])
  end

  # POST /references
  # POST /references.json
  def create
    @reference = current_user.references.new(params[:reference])

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render json: @reference, status: :created, location: @reference }
      else
        format.html { render action: "new" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /references/1
  # PUT /references/1.json
  def update
    @reference = current_user.references.find(params[:id])

    respond_to do |format|
      if @reference.update_attributes(params[:reference])
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference = current_user.references.find(params[:id])
    @reference.destroy

    respond_to do |format|
      format.html { redirect_to references_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_controller_controller.rb
class UserControllerController < ApplicationController
  def show
    if user_signed_in?
      @user = current_user.find(params[:id])
      # If this show page is only for the currently logged in user change it to @user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/business_helper.rb
module BusinessHelper
end

app/helpers/consultant_helper.rb
module ConsultantHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/user_controller_helper.rb
module UserControllerHelper
end

app/views/business/index.html.erb
<div class="container">

  <h1> Welcome to Colaris Consulting </h1>




  <%= link_to '<button type="button" class="btn-custom">Find A Consultant  </button>'.html_safe, '#' %>
  <%= link_to '<button type="button" class="btn-custom">Post a Case </button>'.html_safe, '#' %>
</div>

app/views/consultant/index.html.erb
<div class="container">

  <h1> Welcome to Colaris Consulting </h1>




  <%= link_to '<button type="button" class="btn-custom">Find A Case  </button>'.html_safe, '#' %>
  <%= link_to '<button type="button" class="btn-custom">Edit Your Profile </button>'.html_safe, '#' %>
</div>

app/views/documents/_document.html.erb
    <tr>
      <td><%= document.description %></td>
      <td><%= link_to 'Show', document %></td>
      <td><%= link_to 'Edit', edit_document_path(document) %></td>
      <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

app/views/documents/_form.html.erb
<%= simple_form_for(@document, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>


  <%= f.input :description, as: :text , input_html: {rows:"1"}%>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table class="table table-striped">

  <thead>
    <tr>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
  </thead>
    <tbody>
    <% @documents.each do |document| %>
        <%= render @documents %>

    <% end %>
    </tbody>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<div class="row">
  <div class="span6 offset3">
    <div class="well">
        <p>
            <b>Description:</b>
            <%= @document.description %>
        </p>

        <%= link_to 'Edit', edit_document_path(@document) %> |
        <%= link_to 'Back', documents_path %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class='container'>
<h1>"Colaris is bringing efficincy to the consulting industry across the globe"</h1>
<p1>
Colaris is an online marketplace for businesses and consultants to connect. We cater to the 
needs of consultants, businesses and everyone in between. If you are a consultant, Colaris 
allows you to create a profile and start searching for problems to solve. If you are a business, 
create a profile and begin either searching for a consultant, or post your job for others to bid on. 
</p1>
</div> 

app/views/home/index.html.erb
<div class="container"> 


    <div class="span12">

        <p1 class="span5">
            <h1> Colaris: Connecting Clients and Consultants</h1>
      Our network provides a more efficient way for clients to find Consultants, and for Consultants to reach out to potential
      clients. Colaris allows clients to connect with consultants that better fit their consulting needs. Consultants
      gain exposure to a large network of businesses in need, spending more time on cases and less time searching for
      their next client. Sign up now and get connected to the network that is revolutionizing the consulting industry.
        </p1>
        <div class="span5">

          <%= image_tag "consulting.png" %>


        </div>


    </div>




  </div>

app/views/layouts/_footer.html.erb
<div class="container" >

<p1> 2013 Colaris Consulting, wackerlaura@gmail.COM  </p1>

</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>


                <div class="nav-collapse ">
                    <ul class="nav">

                        <li>

                          <%=link_to 'Colaris', root_path, class:"brand" %>
                        </li>

                        <li>
							<%=link_to 'Home', root_path %>
						</li>
						<li class="dropdown">

                          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Consultants</a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                               <li> <%= link_to "Find Consultants" , href="#"%></li>
                               <li> <%= link_to "Search Consultants", href="#" %></li>

                            </ul>

						</li>
                      <li class="dropdown">

                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Cases</a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                          <li> <%= link_to "Find a Case" , href="#"%></li>
                          <li> <%= link_to "Post a Case", href="#" %></li>
                          <% if user_signed_in? %>
                          <li> <%= link_to "My Cases", href="#" %></li>
                          <%end %>
                        </ul>

                      </li>
						<li>
							<%= link_to 'About Colaris', about_path%>
						</li>
						<li>
							<%= link_to 'Contact Us', '#' %> 
						</li>
					</ul>
                    <ul class="nav pull-right">
                        <% if user_signed_in? %>
                          <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Account</a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                              <li> <%= link_to "Recent Activity" , href="#"%></li>
                              <li> <%= link_to "My Cases", href="#" %></li>
                              <li> <%= link_to "My Network", href='#' %></li>
                              <li> <%=  link_to "My Documents",  %></li>

                            </ul>
                          </li>

                            <li class="dropdown"><%= link_to 'Logout',  destroy_user_session_path, method: :delete %></li>
                            <li><%= link_to 'Edit Profile', edit_user_registration_path,  %></li>
                        <% else  %>
                            <li><%= link_to 'Login',  new_user_session_path %></li>
                            <li><%= link_to 'Create an Account', new_user_registration_path %> </li>
                        <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
  <title>Colaris Consulting</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>
<% flash.each do |name, msg| %>
<%= content_tag(:div, msg, class:"alert alert-#{name}") %>
<%end %>
<div class="container">
    <%= yield %>
</div>
<%= render 'layouts/footer' %>



</body>
</html>

app/views/references/_form.html.erb
<%= simple_form_for(@reference, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstN, label:"First Name" %>
    <%= f.input :lastN, label: "Last Name" %>
    <%= f.input :email %>
    <%= f.input :phone , label:"Phone Number"%>
    <%= f.input :description, label:"Relationship"%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/references/_reference.html.erb
<tr>
  <td><%= reference.firstN %></td>
  <td><%= reference.lastN %></td>
  <td><%= reference.email %></td>
  <td><%= reference.phone %></td>
  <td><%= reference.description %></td>
  <td><%= link_to 'Show', reference %></td>
  <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
  <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/references/edit.html.erb
<h1>Editing reference</h1>

<%= render 'form' %>

<%= link_to 'Show', @reference %> |
<%= link_to 'Back', references_path %>

app/views/references/index.html.erb
<h1>Listing references</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Firstn</th>
    <th>Lastn</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
<% @references.each do |reference| %>
<%=	render @references %>

<% end %>

  </tbody>
</table>

<br />

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<h1>New reference</h1>

<%= render 'form' %>

<%= link_to 'Back', references_path %>

app/views/references/show.html.erb
<p>
  <b>First Name:</b>
  <%= @reference.firstN %>
</p>

<p>
  <b>Last Name:</b>
  <%= @reference.lastN %>
</p>

<p>
  <b>Email:</b>
  <%= @reference.email %>
</p>

<p>
  <b>Phone Number:</b>
  <%= @reference.phone %>
</p>

<p>
  <b>Relation:</b>
  <%= @reference.description %>
</p>




<%= link_to 'Edit', edit_reference_path(@reference) %> |
<%= link_to 'Back', references_path %>